lib/blog_app_web/router.ex
defmodule BlogAppWeb.Router do
  use BlogAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    if Mix.env() == :prod do
      plug CORSPlug, origin: ["https://www.getty104.tk", "http://localhost:45678"]
    else
      plug CORSPlug, origin: "http://localhost:3000"
    end
  end

  scope "/api" do
    pipe_through :api
    forward "/graph", Absinthe.Plug, schema: BlogApp.Blogs.Schema
    options "/graph", Absinthe.Plug, :options
  end

  scope "/admin", as: :admins do
    pipe_through :browser
    resources "/posts", BlogAppWeb.Admins.PostController
    forward "/graphiql", Absinthe.Plug.GraphiQL, schema: BlogApp.Blogs.Schema
  end

  # Other scopes may use custom stacks.
  # scope "/api", BlogAppWeb do
  #   pipe_through :api
  # end
end

lib/blog_app_web/views/layout_view.ex
defmodule BlogAppWeb.LayoutView do
  use BlogAppWeb, :view
end

lib/blog_app_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>BlogApp · Phoenix Framework</title>
  </head>
  <body>
    <section class="hero is-medium is-primary is-bold">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">
            <%= link "Getty's Admin", to: Routes.admins_post_path(@conn, :index) %>
          </h1>
        </div>
      </div>
    </section>
    <main role="main" class="container" style="margin-top: 24px;">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>